name: Build & Test

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'README.md'
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-matrix:
    if: ${{ !(github.event.pull_request.draft || false) }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift-version: ["5.9", "5.8", "5.7"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      if: ${{ !(matrix.os == 'ubuntu-latest') }}
      run: swift test -v
    - name: Test Release
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: swift test -c release -Xswiftc -enable-testing
