name: Build & Test

on:
  schedule:
    - cron: "49 4 * * 1"
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    uses: swift-libp2p/github-workflows/.github/workflows/build+test.yml@main
    with:
      test_in_release_configuration: true
